package XMLCreation;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;


public class CreatePain001XMLFile {
    public static void main(String[] args) throws ParserConfigurationException, TransformerException, ParserConfigurationException, TransformerException {
        DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder docBuilder = docFactory.newDocumentBuilder();
        Document doc = docBuilder.newDocument();
        Element rootelement = doc.createElement("Document");
        String ppp = "urn:iso:std:iso:20022:tech:xsd:pain.001.001.09";
        //String qqq = http://www.w3.org/2001/XMLSchema-instance;
        //String bbb = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.10 file:///D:/workspaceSPAG/IPSProject/InstantAXE/xsd/pacs.002.001.10.xsd";
        //rootelement.setAttribute("xmlns:xsi", qqq);
        rootelement.setAttribute("xmlns", ppp);


        //rootelement.setAttribute("xsi:schemaLocation", bbb);
        doc.appendChild(rootelement);
        int leftLimit = 97; // letter 'a'
        int rightLimit = 122; // letter 'z'
        int targetStringLength = 20;
        Random random = new Random();

        String TempMsgIdText = random.ints(leftLimit, rightLimit + 1)
                .limit(targetStringLength)
                .collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append)
                .toString();
        System.out.println(TempMsgIdText);
        //Creating timestamp
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        SimpleDateFormat aaa = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat ccc = new SimpleDateFormat("yyyyMMdd");
        SimpleDateFormat ddd = new SimpleDateFormat("HHmmss");
        SimpleDateFormat eee = new SimpleDateFormat("HH:mm:ss");
        String formattedDate = sdf.format(date);
        String OnlyDate = aaa.format(date);
        String currdate = formattedDate.replace(" ", "T");
        String Messagetime1 =ccc.format(date);
        String Messagetime2 =ddd.format(date);
        String Messagetime3 = eee.format(date);
        String Messagetime =Messagetime1+"T"+Messagetime2;
        String Messagetime12 =currdate+"T"+Messagetime3;
        String timestamp = Messagetime1+Messagetime2;
        System.out.println(currdate);
        System.out.println(OnlyDate);
        System.out.println(Messagetime);
        String MsgIdText ="INNDNL2U"+Messagetime ;
        System.out.println(MsgIdText);
        //Adding elements to XML
        Element CstmrCdtTrfInitn = doc.createElement("CstmrCdtTrfInitn");
        rootelement.appendChild(CstmrCdtTrfInitn);
        Element GrpHdr = doc.createElement("GrpHdr");
        CstmrCdtTrfInitn.appendChild(GrpHdr);
        Element MsgId = doc.createElement("MsgId");
        GrpHdr.appendChild(MsgId);
        MsgId.setTextContent(MsgIdText);
        Element CreDtTm = doc.createElement("CreDtTm");
        GrpHdr.appendChild(CreDtTm);
        CreDtTm.setTextContent(currdate);
        Element NbOfTxs = doc.createElement("NbOfTxs");
        GrpHdr.appendChild(NbOfTxs);
        NbOfTxs.setTextContent("3");
        Element CtrlSum = doc.createElement("CtrlSum");
        GrpHdr.appendChild(CtrlSum);
        CtrlSum.setTextContent("15.12");
        Element InitgPty = doc.createElement("InitgPty");
        GrpHdr.appendChild(InitgPty);
        Element Id = doc.createElement("Id");
        InitgPty.appendChild(Id);
        Element OrgId = doc.createElement("OrgId");
        Id.appendChild(OrgId);
        Element AnyBIC = doc.createElement("AnyBIC");
        OrgId.appendChild(AnyBIC);
        AnyBIC.setTextContent("NNBANL2G");
        Element PmtInf = doc.createElement("PmtInf");
        CstmrCdtTrfInitn.appendChild(PmtInf);
        Element PmtInfId = doc.createElement("PmtInfId");
        PmtInf.appendChild(PmtInfId);
        PmtInfId.setTextContent("28702354");
        Element PmtMtd = doc.createElement("PmtMtd");
        PmtInf.appendChild(PmtMtd);
        PmtMtd.setTextContent("TRF");
        Element BtchBookg = doc.createElement("BtchBookg");
        PmtInf.appendChild(BtchBookg);
        BtchBookg.setTextContent("false");
        Element NbOfTxs1 = doc.createElement("NbOfTxs");
        PmtInf.appendChild(NbOfTxs1);
        NbOfTxs1.setTextContent("1");
        Element CtrlSum1 = doc.createElement("CtrlSum");
        PmtInf.appendChild(CtrlSum1);
        CtrlSum1.setTextContent("5.04");
        Element PmtTpInf = doc.createElement("PmtTpInf");
        PmtInf.appendChild(PmtTpInf);
        Element SvcLvl = doc.createElement("SvcLvl");
        PmtTpInf.appendChild(SvcLvl);
        Element Cd = doc.createElement("Cd");
        SvcLvl.appendChild(Cd);
        Cd.setTextContent("SEPA");
        Element ReqdExctnDt = doc.createElement("ReqdExctnDt");
        PmtInf.appendChild(ReqdExctnDt);
        Element Dt = doc.createElement("Dt");
        ReqdExctnDt.appendChild(Dt);
        Dt.setTextContent(OnlyDate);
        Element Dbtr3 = doc.createElement("Dbtr");
        PmtInf.appendChild(Dbtr3);
        Element Nm = doc.createElement("Nm");
        Dbtr3.appendChild(Nm);
        Nm.setTextContent("Debtor 0");
        Element PstlAdr = doc.createElement("PstlAdr");
        Dbtr3.appendChild(PstlAdr);
        Element Dept = doc.createElement("Dept");
        PstlAdr.appendChild(Dept);
        Dept.setTextContent("Bank");
        Element SubDept = doc.createElement("SubDept");
        PstlAdr.appendChild(SubDept);
        SubDept.setTextContent("Payments");
        Element StrtNm = doc.createElement("StrtNm");
        PstlAdr.appendChild(StrtNm);
        StrtNm.setTextContent("Milkyway");
        Element BldgNb = doc.createElement("BldgNb");
        PstlAdr.appendChild(BldgNb);
        BldgNb.setTextContent("35");
        Element BldgNm = doc.createElement("BldgNm");
        PstlAdr.appendChild(BldgNm);
        BldgNm.setTextContent("Haagsepoort");
        Element Flr = doc.createElement("Flr");
        PstlAdr.appendChild(Flr);
        Flr.setTextContent("10");
        Element PstBx = doc.createElement("PstBx");
        PstlAdr.appendChild(PstBx);
        PstBx.setTextContent("1000");
        Element Room = doc.createElement("Room");
        PstlAdr.appendChild(Room);
        Room.setTextContent("D");
        Element PstCd = doc.createElement("PstCd");
        PstlAdr.appendChild(PstCd);
        PstCd.setTextContent("2595AK");
        Element TwnNm = doc.createElement("TwnNm");
        PstlAdr.appendChild(TwnNm);
        TwnNm.setTextContent("Den Haag");
        Element TwnLctnNm = doc.createElement("TwnLctnNm");
        PstlAdr.appendChild(TwnLctnNm);
        TwnLctnNm.setTextContent("Muziekbuurt");
        Element DstrctNm = doc.createElement("DstrctNm");
        PstlAdr.appendChild(DstrctNm);
        DstrctNm.setTextContent("Rijswijk");
        Element CtrySubDvsn = doc.createElement("CtrySubDvsn");
        PstlAdr.appendChild(CtrySubDvsn);
        CtrySubDvsn.setTextContent("Zuid-Holland");
        Element Ctry = doc.createElement("Ctry");
        PstlAdr.appendChild(Ctry);
        Ctry.setTextContent("NL");
        Element Id1 = doc.createElement("Id");
        Dbtr3.appendChild(Id1);
        Element OrgId1 = doc.createElement("OrgId");
        Id1.appendChild(OrgId1);
        Element Othr = doc.createElement("Othr");
        OrgId1.appendChild(Othr);
        Element Id2 = doc.createElement("Id");
        Othr.appendChild(Id2);
        Id2.setTextContent("2444407");
        Element DbtrAcct = doc.createElement("DbtrAcct");
        PmtInf.appendChild(DbtrAcct);
        Element Id3 = doc.createElement("Id");
        DbtrAcct.appendChild(Id3);
        Element IBAN = doc.createElement("IBAN");
        Id3.appendChild(IBAN);
        IBAN.setTextContent("NL97NNBA2022645367");
        Element DbtrAgt = doc.createElement("DbtrAgt");
        PmtInf.appendChild(DbtrAgt);
        Element FinInstnId =doc.createElement("FinInstnId");
        DbtrAgt.appendChild(FinInstnId);
        Element BICFI =doc.createElement("BICFI");
        FinInstnId.appendChild(BICFI);
        BICFI.setTextContent("NNBANL2G");
        Element ChrgBr = doc.createElement("ChrgBr");
        PmtInf.appendChild(ChrgBr);
        ChrgBr.setTextContent("SLEV");
        Element CdtTrfTxInf = doc.createElement("CdtTrfTxInf");
        PmtInf.appendChild(CdtTrfTxInf);
        Element PmtId = doc.createElement("PmtId");
        CdtTrfTxInf.appendChild(PmtId);
        Element EndToEndId = doc.createElement("EndToEndId");
        PmtId.appendChild(EndToEndId);
        EndToEndId.setTextContent("19872317");
        Element Amt = doc.createElement("Amt");
        CdtTrfTxInf.appendChild(Amt);
        Element InstdAmt  = doc.createElement("InstdAmt");
        Amt.appendChild(InstdAmt);
        InstdAmt.setAttribute("Ccy", "EUR");
        InstdAmt.setTextContent("5.04");
        Element CdtrAgt = doc.createElement("CdtrAgt");
        CdtTrfTxInf.appendChild(CdtrAgt);
        Element FinInstnId1 = doc.createElement("FinInstnId");
        CdtrAgt.appendChild(FinInstnId1);
        Element BICFI1 = doc.createElement("BICFI");
        FinInstnId1.appendChild(BICFI1);
        BICFI1.setTextContent("SNSBNL2A");
        Element Cdtr = doc.createElement("Cdtr");
        CdtTrfTxInf.appendChild(Cdtr);
        Element Nm1 = doc.createElement("Nm");
        Cdtr.appendChild(Nm1);
        Nm1.setTextContent("Creditor 0");
        Element CdtrAcct = doc.createElement("CdtrAcct");
        CdtTrfTxInf.appendChild(CdtrAcct);
        Element Id4 = doc.createElement("Id");
        CdtrAcct.appendChild(Id4);
        Element IBAN1 = doc.createElement("IBAN");
        Id4.appendChild(IBAN1);
        IBAN1.setTextContent("NL48SNSB0119930676");
        Element RmtInf = doc.createElement("RmtInf");
        CdtTrfTxInf.appendChild(RmtInf);
        Element Ustrd = doc.createElement("Ustrd");
        RmtInf.appendChild(Ustrd);
        Ustrd.setTextContent("Payment Galaxy generated 0");
        Element PmtInf1 = doc.createElement("PmtInf");
        CstmrCdtTrfInitn.appendChild(PmtInf1);
        Element PmtInfId1 = doc.createElement("PmtInfId");
        PmtInf1.appendChild(PmtInfId1);
        PmtInfId1.setTextContent("53587215");
        Element PmtMtd1 = doc.createElement("PmtMtd");
        PmtInf1.appendChild(PmtMtd1);
        PmtMtd1.setTextContent("TRF");
        Element BtchBookg1 = doc.createElement("BtchBookg");
        PmtInf1.appendChild(BtchBookg1);
        BtchBookg1.setTextContent("false");
        Element NbOfTxs2 = doc.createElement("NbOfTxs");
        PmtInf1.appendChild(NbOfTxs2);
        NbOfTxs2.setTextContent("1");
        Element CtrlSum2 = doc.createElement("CtrlSum");
        PmtInf1.appendChild(CtrlSum2);
        CtrlSum2.setTextContent("5.05");
        Element PmtTpInf1 = doc.createElement("PmtTpInf");
        PmtInf1.appendChild(PmtTpInf1);
        Element SvcLvl1 = doc.createElement("SvcLvl");
        PmtTpInf1.appendChild(SvcLvl1);
        Element Cd1 = doc.createElement("Cd");
        SvcLvl1.appendChild(Cd1);
        Cd1.setTextContent("SEPA");
        Element ReqdExctnDt1 = doc.createElement("ReqdExctnDt");
        PmtInf1.appendChild(ReqdExctnDt1);
        Element Dt1 = doc.createElement("Dt");
        ReqdExctnDt1.appendChild(Dt1);
        Dt1.setTextContent(OnlyDate);
        Element Dbtr1 = doc.createElement("Dbtr");
        PmtInf1.appendChild(Dbtr1);
        Element Nm2 = doc.createElement("Nm");
        Dbtr1.appendChild(Nm2);
        Nm2.setTextContent("Debtor 1");
        Element PstlAdr1 = doc.createElement("PstlAdr");
        Dbtr1.appendChild(PstlAdr1);
        Element Dept1 = doc.createElement("Dept");
        PstlAdr1.appendChild(Dept1);
        Dept1.setTextContent("Bank");
        Element SubDept1 = doc.createElement("SubDept");
        PstlAdr1.appendChild(SubDept1);
        SubDept1.setTextContent("Payments");
        Element StrtNm1 = doc.createElement("StrtNm");
        PstlAdr1.appendChild(StrtNm1);
        StrtNm1.setTextContent("Milkyway");
        Element BldgNb1 = doc.createElement("BldgNb");
        PstlAdr1.appendChild(BldgNb1);
        BldgNb1.setTextContent("35");
        Element BldgNm1 = doc.createElement("BldgNm");
        PstlAdr1.appendChild(BldgNm1);
        BldgNm1.setTextContent("Haagsepoort");
        Element Flr1 = doc.createElement("Flr");
        PstlAdr1.appendChild(Flr1);
        Flr1.setTextContent("10");
        Element PstBx1 = doc.createElement("PstBx");
        PstlAdr1.appendChild(PstBx1);
        PstBx1.setTextContent("1000");
        Element Room1 = doc.createElement("Room");
        PstlAdr1.appendChild(Room1);
        Room1.setTextContent("D");
        Element PstCd1 = doc.createElement("PstCd");
        PstlAdr1.appendChild(PstCd1);
        PstCd1.setTextContent("2595AK");
        Element TwnNm1 = doc.createElement("TwnNm");
        PstlAdr1.appendChild(TwnNm1);
        TwnNm1.setTextContent("Den Haag");
        Element TwnLctnNm1 = doc.createElement("TwnLctnNm");
        PstlAdr1.appendChild(TwnLctnNm1);
        TwnLctnNm1.setTextContent("Muziekbuurt");
        Element DstrctNm1 = doc.createElement("DstrctNm");
        PstlAdr1.appendChild(DstrctNm1);
        DstrctNm1.setTextContent("Rijswijk");
        Element CtrySubDvsn1 = doc.createElement("CtrySubDvsn");
        PstlAdr1.appendChild(CtrySubDvsn1);
        CtrySubDvsn1.setTextContent("Zuid-Holland");
        Element Ctry1 = doc.createElement("Ctry");
        PstlAdr1.appendChild(Ctry1);
        Ctry1.setTextContent("NL");
        Element Id11 = doc.createElement("Id");
        Dbtr1.appendChild(Id11);
        Element OrgId11 = doc.createElement("OrgId");
        Id11.appendChild(OrgId11);
        Element Othr11 = doc.createElement("Othr");
        OrgId11.appendChild(Othr11);
        Element Id21 = doc.createElement("Id");
        Othr11.appendChild(Id21);
        Id21.setTextContent("4037773");
        Element DbtrAcct11 = doc.createElement("DbtrAcct");
        PmtInf1.appendChild(DbtrAcct11);
        Element Id31 = doc.createElement("Id");
        DbtrAcct11.appendChild(Id31);
        Element IBAN11 = doc.createElement("IBAN");
        Id31.appendChild(IBAN11);
        IBAN11.setTextContent("NL02NNBA3188204897");
        Element DbtrAgt11 = doc.createElement("DbtrAgt");
        PmtInf1.appendChild(DbtrAgt11);
        Element FinInstnId11 =doc.createElement("FinInstnId");
        DbtrAgt11.appendChild(FinInstnId11);
        Element BICFI11 =doc.createElement("BICFI");
        FinInstnId11.appendChild(BICFI11);
        BICFI11.setTextContent("NNBANL2G");
        Element ChrgBr11 = doc.createElement("ChrgBr");
        PmtInf1.appendChild(ChrgBr11);
        ChrgBr11.setTextContent("SLEV");
        Element CdtTrfTxInf11 = doc.createElement("CdtTrfTxInf");
        PmtInf1.appendChild(CdtTrfTxInf11);
        Element PmtId11 = doc.createElement("PmtId");
        CdtTrfTxInf11.appendChild(PmtId11);
        Element EndToEndId11 = doc.createElement("EndToEndId");
        PmtId11.appendChild(EndToEndId11);
        EndToEndId11.setTextContent("30286147");
        Element Amt11 = doc.createElement("Amt");
        CdtTrfTxInf11.appendChild(Amt11);
        Element InstdAmt11  = doc.createElement("InstdAmt");
        Amt11.appendChild(InstdAmt11);
        InstdAmt11.setAttribute("Ccy", "EUR");
        InstdAmt11.setTextContent("5.04");
        Element CdtrAgt11 = doc.createElement("CdtrAgt");
        CdtTrfTxInf.appendChild(CdtrAgt11);
        Element FinInstnId12 = doc.createElement("FinInstnId");
        CdtrAgt11.appendChild(FinInstnId12);
        Element BICFI12 = doc.createElement("BICFI");
        FinInstnId12.appendChild(BICFI12);
        BICFI12.setTextContent("SNSBNL2A");
        Element Cdtr11 = doc.createElement("Cdtr");
        CdtTrfTxInf11.appendChild(Cdtr11);
        Element Nm11 = doc.createElement("Nm");
        Cdtr11.appendChild(Nm11);
        Nm11.setTextContent("Creditor 1");
        Element CdtrAcct11 = doc.createElement("CdtrAcct");
        CdtTrfTxInf11.appendChild(CdtrAcct11);
        Element Id41 = doc.createElement("Id");
        CdtrAcct11.appendChild(Id41);
        Element IBAN12 = doc.createElement("IBAN");
        Id41.appendChild(IBAN12);
        IBAN12.setTextContent("NL48SNSB0119930676");
        Element RmtInf11 = doc.createElement("RmtInf");
        CdtTrfTxInf11.appendChild(RmtInf11);
        Element Ustrd11 = doc.createElement("Ustrd");
        RmtInf11.appendChild(Ustrd11);
        Ustrd11.setTextContent("Payment Galaxy generated 1");
        Element PmtInf2 = doc.createElement("PmtInf");
        CstmrCdtTrfInitn.appendChild(PmtInf2);
        Element PmtInfId2 = doc.createElement("PmtInfId");
        PmtInf2.appendChild(PmtInfId2);
        PmtInfId2.setTextContent("53587225");
        Element PmtMtd2 = doc.createElement("PmtMtd");
        PmtInf2.appendChild(PmtMtd2);
        PmtMtd2.setTextContent("TRF");
        Element BtchBookg2 = doc.createElement("BtchBookg");
        PmtInf2.appendChild(BtchBookg2);
        BtchBookg2.setTextContent("false");
        Element NbOfTxs21 = doc.createElement("NbOfTxs");
        PmtInf2.appendChild(NbOfTxs21);
        NbOfTxs21.setTextContent("2");
        Element CtrlSum21 = doc.createElement("CtrlSum");
        PmtInf2.appendChild(CtrlSum21);
        CtrlSum21.setTextContent("5.05");
        Element PmtTpInf2 = doc.createElement("PmtTpInf");
        PmtInf2.appendChild(PmtTpInf2);
        Element SvcLvl2 = doc.createElement("SvcLvl");
        PmtTpInf2.appendChild(SvcLvl2);
        Element Cd2 = doc.createElement("Cd");
        SvcLvl2.appendChild(Cd2);
        Cd2.setTextContent("SEPA");
        Element ReqdExctnDt2 = doc.createElement("ReqdExctnDt");
        PmtInf2.appendChild(ReqdExctnDt2);
        Element Dt2 = doc.createElement("Dt");
        ReqdExctnDt2.appendChild(Dt2);
        Dt2.setTextContent(OnlyDate);
        Element Dbtr2 = doc.createElement("Dbtr");
        PmtInf2.appendChild(Dbtr2);
        Element Nm21 = doc.createElement("Nm");
        Dbtr2.appendChild(Nm21);
        Nm21.setTextContent("Debtor 2");
        Element PstlAdr2 = doc.createElement("PstlAdr");
        Dbtr2.appendChild(PstlAdr2);
        Element Dept2 = doc.createElement("Dept");
        PstlAdr2.appendChild(Dept2);
        Dept2.setTextContent("Bank");
        Element SubDept2 = doc.createElement("SubDept");
        PstlAdr2.appendChild(SubDept2);
        SubDept2.setTextContent("Payments");
        Element StrtNm2 = doc.createElement("StrtNm");
        PstlAdr2.appendChild(StrtNm2);
        StrtNm2.setTextContent("Milkyway");
        Element BldgNb2 = doc.createElement("BldgNb");
        PstlAdr2.appendChild(BldgNb2);
        BldgNb2.setTextContent("35");
        Element BldgNm2 = doc.createElement("BldgNm");
        PstlAdr2.appendChild(BldgNm2);
        BldgNm2.setTextContent("Haagsepoort");
        Element Flr2 = doc.createElement("Flr");
        PstlAdr2.appendChild(Flr2);
        Flr2.setTextContent("20");
        Element PstBx2 = doc.createElement("PstBx");
        PstlAdr2.appendChild(PstBx2);
        PstBx2.setTextContent("2000");
        Element Room2 = doc.createElement("Room");
        PstlAdr2.appendChild(Room2);
        Room2.setTextContent("D");
        Element PstCd2 = doc.createElement("PstCd");
        PstlAdr2.appendChild(PstCd2);
        PstCd2.setTextContent("2595AK");
        Element TwnNm2 = doc.createElement("TwnNm");
        PstlAdr2.appendChild(TwnNm2);
        TwnNm2.setTextContent("Den Haag");
        Element TwnLctnNm2 = doc.createElement("TwnLctnNm");
        PstlAdr2.appendChild(TwnLctnNm2);
        TwnLctnNm2.setTextContent("Muziekbuurt");
        Element DstrctNm2 = doc.createElement("DstrctNm");
        PstlAdr2.appendChild(DstrctNm2);
        DstrctNm2.setTextContent("Rijswijk");
        Element CtrySubDvsn2 = doc.createElement("CtrySubDvsn");
        PstlAdr2.appendChild(CtrySubDvsn2);
        CtrySubDvsn2.setTextContent("Zuid-Holland");
        Element Ctry2 = doc.createElement("Ctry");
        PstlAdr2.appendChild(Ctry2);
        Ctry2.setTextContent("NL");
        Element Id22 = doc.createElement("Id");
        Dbtr2.appendChild(Id22);
        Element OrgId22 = doc.createElement("OrgId");
        Id22.appendChild(OrgId22);
        Element Othr22 = doc.createElement("Othr");
        OrgId22.appendChild(Othr22);
        Element Id221 = doc.createElement("Id");
        Othr22.appendChild(Id221);
        Id221.setTextContent("4037773");
        Element DbtrAcct22 = doc.createElement("DbtrAcct");
        PmtInf2.appendChild(DbtrAcct22);
        Element Id32 = doc.createElement("Id");
        DbtrAcct22.appendChild(Id32);
        Element IBAN22 = doc.createElement("IBAN");
        Id32.appendChild(IBAN22);
        IBAN22.setTextContent("NL02NNBA3288204897");
        Element DbtrAgt22 = doc.createElement("DbtrAgt");
        PmtInf2.appendChild(DbtrAgt22);
        Element FinInstnId22 =doc.createElement("FinInstnId");
        DbtrAgt22.appendChild(FinInstnId22);
        Element BICFI22 =doc.createElement("BICFI");
        FinInstnId22.appendChild(BICFI22);
        BICFI22.setTextContent("NNBANL2G");
        Element ChrgBr22 = doc.createElement("ChrgBr");
        PmtInf2.appendChild(ChrgBr22);
        ChrgBr22.setTextContent("SLEV");
        Element CdtTrfTxInf22 = doc.createElement("CdtTrfTxInf");
        PmtInf2.appendChild(CdtTrfTxInf22);
        Element PmtId22 = doc.createElement("PmtId");
        CdtTrfTxInf22.appendChild(PmtId22);
        Element EndToEndId22 = doc.createElement("EndToEndId");
        PmtId22.appendChild(EndToEndId22);
        EndToEndId22.setTextContent("30286247");
        Element Amt22 = doc.createElement("Amt");
        CdtTrfTxInf22.appendChild(Amt22);
        Element InstdAmt22  = doc.createElement("InstdAmt");
        Amt22.appendChild(InstdAmt22);
        InstdAmt22.setAttribute("Ccy", "EUR");
        InstdAmt22.setTextContent("5.04");
        Element CdtrAgt22 = doc.createElement("CdtrAgt");
        CdtTrfTxInf.appendChild(CdtrAgt22);
        Element FinInstnId221 = doc.createElement("FinInstnId");
        CdtrAgt22.appendChild(FinInstnId221);
        Element BICFI221 = doc.createElement("BICFI");
        FinInstnId221.appendChild(BICFI221);
        BICFI221.setTextContent("SNSBNL2A");
        Element Cdtr22 = doc.createElement("Cdtr");
        CdtTrfTxInf22.appendChild(Cdtr22);
        Element Nm22 = doc.createElement("Nm");
        Cdtr22.appendChild(Nm22);
        Nm22.setTextContent("Creditor 2");
        Element CdtrAcct22 = doc.createElement("CdtrAcct");
        CdtTrfTxInf22.appendChild(CdtrAcct22);
        Element Id42 = doc.createElement("Id");
        CdtrAcct22.appendChild(Id42);
        Element IBAN221 = doc.createElement("IBAN");
        Id42.appendChild(IBAN221);
        IBAN221.setTextContent("NL48SNSB0229930676");
        Element RmtInf22 = doc.createElement("RmtInf");
        CdtTrfTxInf22.appendChild(RmtInf22);
        Element Ustrd22 = doc.createElement("Ustrd");
        RmtInf22.appendChild(Ustrd22);
        Ustrd22.setTextContent("Payment Galaxy generated 2");













        TransformerFactory transformerFactory = TransformerFactory.newInstance();
        Transformer transformer = transformerFactory.newTransformer();
        transformer.setOutputProperty(OutputKeys.INDENT, "yes");
        transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes");
        DOMSource source = new DOMSource(doc);
        StreamResult result = new StreamResult(new File("PAIN001.xml"));
        transformer.transform(source, result);


    }


}
